version: '2'
services:
  daemon:
    hostname: daemon
    image: quay.io/parkervcp/pterodactyl-daemon
    ports:
      - "8080:8080"
    tty: true
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/daemon/config/core.json:/srv/daemon/config/core.json"
      - "/srv/daemon/config/servers/:/srv/daemon/config/servers/"
      - "/srv/daemon/config/credentials/:/srv/daemon/config/credentials/"
      - "/srv/daemon-data/:/srv/daemon-data/"